# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chuck' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chuck
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'RxAtomic',   '~> 4.0'

end
